#include "MontageGraphDelegates.h"

FMontageGraphDelegates::FOnMontageGraphEvaluated FMontageGraphDelegates::OnGraphNodeEvaluated;
FMontageGraphDelegates::FOnMontageGraphSelected FMontageGraphDelegates::OnGraphNodeSelected;
FMontageGraphDelegates::FOnMontageGraphReset FMontageGraphDelegates::OnGraphReset;
FMontageGraphDelegates::FOnMontageGraphNodeEvaluated FMontageGraphDelegates::OnNodeEvaluated;


#if WITH_EDITORONLY_DATA
#endif

